security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    role_hierarchy:
        ROLE_ADMIN: [ROLE_RH, ROLE_USER]
        ROLE_RH: [ROLE_USER]

    providers:
        app_user_provider:
            id: App\Security\InMemoryUserProvider

    firewalls:
        dev:
            pattern: ^/_(profiler|wdt)
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                username_parameter: email
                password_parameter: password
                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
                always_use_default_target_path: true
                use_referer: false
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/rh, roles: ROLE_RH }
